services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.5.5
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
      - WEBUI_PORT=8080
      - UMASK=002
      - QBT_WEBUI_USERNAME=admin
      - QBT_WEBUI_PASSWORD=adminadmin
    volumes:
      - ./config/qbittorrent:/config
      - ./Media:/downloads
    ports:
      - '8080:8080'
      - '6881:6881'
      - '6881:6881/udp'
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:5.0.3
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
    volumes:
      - ./config/radarr:/config
      - ./Media/Movies:/movies
      - ./Media:/downloads
    ports:
      - '7878:7878'
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:3.0.10
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
    volumes:
      - ./config/sonarr:/config
      - ./Media/Series:/tv
      - ./Media:/downloads
    ports:
      - '8989:8989'
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
    volumes:
      - ./config/prowlarr:/config
    ports:
      - '9696:9696'
    restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    ports:
      - '8191:8191'
    restart: unless-stopped
